---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/k3sup version
    register: k3sup_test_output
  - name: k3sup version
    debug:
      msg: '{{ k3sup_test_output.stdout }}'
