---
- name: Installing andrewrothstein.k3sup
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Execution 'k3sup version'
      ansible.builtin.command: /usr/local/bin/k3sup version
      changed_when: false
      register: k3sup_test_output
    - name: Output from 'k3sup version'
      ansible.builtin.debug:
        msg: '{{ k3sup_test_output.stdout }}'
